### ISSUE TITLE
installing on mac osx?

### ISSUE THREAD

**Issue by julia-ex** [jtsiomb/fsnav#1]
Hi there. I’m a designer, not a comp sci person, and reading/executing code is not my strong suit, so please bear with me.
I’m trying to install this file navigator on my MacBook (running Mojave 10.14.6) but I’m stuck in a loop of needing to install dependencies, and then dependencies for the dependencies. I’ve looked at similar repos and tutorials to try and troubleshoot on my own, but they’re all from several years ago so it seems like the dependency lineup may well have changed. Any recommendations about if/how to get this up and running on a MacBook?

**Comment by jtsiomb** [comment]
Hello.

This is not the place for tech support. I'd like to keep the issues tracker just for people who find problems with the program itself.

Please send me an email (address is in the readme file) with details of exactly where you're stuck, which dependency you're trying to install and what's going wrong with it, and I'll try to help.
